"""서빙 코드 생성·빌드 도구 테스트 — 파이프라인을 실행하지 않는 정적 검증.

`serving/_core.py` 는 `tools/build_serving_core.py` 가 src 원문에서 **추출해 생성**한다.
학습(노트북)과 서빙이 다른 피처를 만드는 드리프트를 막는 장치이므로 다음을 강제한다.

- 생성 파일이 src 와 바이트 단위로 동기(`--check`), LF 줄바꿈, 자동생성 헤더
- 추출된 모든 정의의 AST 가 src 원문 정의의 AST 와 같다 (src 는 `ast.parse` 만 — import 금지)
- `_core` import 에 부작용(파일 생성)이 없다

함께 10.5절(모델 번들)에 맞춰 바뀐 빌드 도구의 규칙도 점검한다.
노트북 금지 패턴(`validate`), 최종 게이트 강제(`check_final_gate`), 재현성 비교 대상
(`ch6_model_bundles`), 개인정보 스캔 정규식(`PRIVACY_PATTERNS`).

⚠️ 이 파일의 테스트는 s00~s10 fixture(=파이프라인 실행)를 쓰지 않는다. 또한
`build_notebook.main()`(노트북 덮어쓰기)·`build_serving_core.main([])`(생성 파일 덮어쓰기)·
`check_reproducibility.main()`(파이프라인 재실행) 을 호출하지 않는다.
"""
from __future__ import annotations

import ast
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import nbformat
import pandas as pd
import pytest

# serving/ 이 없는 환경(노트북·데이터만 받은 경우)에서는 이 모듈을 통째로 건너뛴다
pytest.importorskip("serving")

import build_notebook  # noqa: E402
import build_serving_core
import check_reproducibility
import finalize_notebook

PROJECT_ROOT = build_serving_core.PROJECT_ROOT
CORE_PATH = PROJECT_ROOT / "serving" / "_core.py"

# SPEC 의 (원본 파일, 이름) 전부 — 함수·상수 모두 원문과 같아야 한다
SPEC_ITEMS = [(rel, name) for rel, names in build_serving_core.SPEC for name in names]

# 서빙 코어에 반드시 있어야 하는 핵심 정의(SPEC 에서 빠지면 서빙이 깨진다)
REQUIRED_CORE_NAMES = {
    "restore_hours", "build_datetime_index", "flag_and_repair", "add_targets",
    "build_operating_calendar", "build_features", "bundle_predict",
}

LGB_FILE_API = "LightGBM 파일 API 금지(model_str 사용)"
SERVING_IMPORT = "serving 패키지 import 금지(자기완결)"


def _defining_node(tree: ast.Module, name: str) -> ast.stmt | None:
    """모듈 최상위에서 `name` 을 정의하는 문장(def·class·대입)을 찾는다."""
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and node.name == name:
            return node
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == name for t in node.targets
        ):
            return node
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == name:
            return node
    return None


def _core_tree() -> ast.Module:
    """생성된 `serving/_core.py` 의 AST."""
    return ast.parse(CORE_PATH.read_bytes().decode("utf-8"))


def _code_nb(*sources: str, markdown: tuple[str, ...] = ()) -> nbformat.NotebookNode:
    """코드 셀(과 선택적 마크다운 셀)로 합성 노트북을 만든다."""
    cells = [nbformat.v4.new_markdown_cell(m) for m in markdown]
    cells += [nbformat.v4.new_code_cell(s) for s in sources]
    return nbformat.v4.new_notebook(cells=cells)


# ══════════════════════════════════════════════════════════════════════
# 1~3 — 생성 파일의 동기화·형식
# ══════════════════════════════════════════════════════════════════════
def test_generated_core_in_sync_with_src():
    """`build_serving_core --check` 가 0 이다 — 생성 파일이 src 원문과 바이트 단위로 같다."""
    assert build_serving_core.main(["--check"]) == 0, "python tools/build_serving_core.py 로 다시 생성하라"


def test_render_equals_committed_bytes():
    """`render()` 결과(UTF-8)가 커밋된 `_core.py` 바이트와 같다."""
    assert build_serving_core.render().encode("utf-8") == CORE_PATH.read_bytes()


def test_render_has_no_free_names():
    """생성 코드가 참조하는 전역 이름이 모두 생성 파일 안에 정의돼 있다."""
    assert build_serving_core.free_names(build_serving_core.render()) == set()


def test_free_names_detects_undefined_global():
    """`free_names` 가 실제로 미정의 전역을 잡는다 — 위 테스트가 공허하지 않다는 근거."""
    code = (
        "import numpy as np\n"
        "LOCAL_CONST = 1\n"
        "def f(a, *args, k=None, **kw):\n"
        "    import math\n"
        "    b = [x for x in range(a)]\n"
        "    def inner(y):\n"
        "        return y\n"
        "    return inner(len(b)) + LOCAL_CONST + math.pi + np.pi + MISSING_CONST\n"
    )
    assert build_serving_core.free_names(code) == {"MISSING_CONST"}


def test_core_is_lf_only():
    """`_core.py` 에 CRLF 가 없다 — Windows 에서 생성해도 리눅스 서버와 바이트가 같다."""
    assert b"\r\n" not in CORE_PATH.read_bytes()


def test_core_has_autogenerated_header():
    """`_core.py` 첫머리에 자동생성 표시가 있다(직접 수정 금지)."""
    head = CORE_PATH.read_bytes().decode("utf-8").splitlines()[0]
    assert "AUTO-GENERATED" in head
    assert "build_serving_core.py" in head


def test_check_fails_when_core_differs(tmp_path, monkeypatch):
    """생성 파일이 src 와 다르거나 없으면 `--check` 가 1 을 돌려준다(쓰지 않는다)."""
    fake = tmp_path / "_core.py"
    fake.write_bytes(build_serving_core.render().encode("utf-8") + b"# drift\n")
    monkeypatch.setattr(build_serving_core, "OUTPUT", fake)
    before = fake.read_bytes()
    assert build_serving_core.main(["--check"]) == 1
    assert fake.read_bytes() == before, "--check 가 파일을 고쳐 썼다"

    monkeypatch.setattr(build_serving_core, "OUTPUT", tmp_path / "없음" / "_core.py")
    assert build_serving_core.main(["--check"]) == 1
    assert not (tmp_path / "없음").exists()


# ══════════════════════════════════════════════════════════════════════
# 4 — 추출 정의의 AST 가 src 원문과 같다
# ══════════════════════════════════════════════════════════════════════
@pytest.mark.parametrize("relpath,name", SPEC_ITEMS, ids=[f"{Path(r).stem}::{n}" for r, n in SPEC_ITEMS])
def test_core_definition_ast_matches_src(relpath, name):
    """`_core` 의 정의가 src 파일의 같은 이름 최상위 정의와 AST 가 같다(데코레이터 포함)."""
    src_tree = ast.parse((PROJECT_ROOT / relpath).read_text(encoding="utf-8"))
    src_node = _defining_node(src_tree, name)
    core_node = _defining_node(_core_tree(), name)
    assert src_node is not None, f"{relpath} 에 최상위 '{name}' 이 없다"
    assert core_node is not None, f"_core.py 에 '{name}' 이 없다"
    assert ast.dump(core_node) == ast.dump(src_node), f"'{name}' 이 {relpath} 원문과 다르다"


def test_core_defines_exactly_spec_names():
    """`_core` 최상위 정의 = SPEC 이름 전부, 각 한 번씩 — 누락·중복·잉여 정의가 없다."""
    defined = []
    for node in _core_tree().body:
        defined += build_serving_core._top_level_names(node)
    spec_names = [n for _, n in SPEC_ITEMS]
    assert sorted(defined) == sorted(spec_names)
    assert len(set(defined)) == len(defined), "같은 이름이 두 번 정의됐다"
    assert REQUIRED_CORE_NAMES <= set(defined)


def test_core_top_level_has_only_imports_and_definitions():
    """`_core` 최상위에는 import(numpy·pandas)·정의·대입·docstring 만 있다 — 실행 문장이 없다."""
    tree = _core_tree()
    imported = set()
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            imported |= {a.name for a in node.names}
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            continue   # 모듈 docstring
        assert isinstance(node, (ast.FunctionDef, ast.Assign, ast.AnnAssign)), (
            f"{node.lineno}행: 최상위 실행 문장 {type(node).__name__}"
        )
    # numpy·pandas + 매니페스트 해시용 표준 라이브러리(hashlib·json)만
    assert imported == {"numpy", "pandas", "hashlib", "json"}


# ══════════════════════════════════════════════════════════════════════
# 5 — import 부작용 없음
# ══════════════════════════════════════════════════════════════════════
def test_core_import_has_no_side_effects(tmp_path):
    """복사한 `serving._core` 를 별도 프로세스에서 import 해도 작업 폴더에 새 파일이 생기지 않는다."""
    # 메인 트리 outputs/ 는 FULL 실행 중 계속 바뀌므로, `_core.py` 를 tmp 로 복사하고
    # CWD 도 tmp 로 둔 채 import 해 tmp 안의 파일 목록(mtime 포함) 변화로 판정한다.
    # 바이트코드 캐시(__pycache__)는 파이썬 자체의 동작이므로 `-B` 로 끈다.
    pkg = tmp_path / "serving"
    pkg.mkdir()
    (pkg / "__init__.py").write_bytes(b"")
    shutil.copyfile(CORE_PATH, pkg / "_core.py")

    def listing() -> list[tuple[str, int, int]]:
        return sorted(
            (p.relative_to(tmp_path).as_posix(), p.stat().st_mtime_ns, p.stat().st_size)
            for p in tmp_path.rglob("*")
        )

    before = listing()
    env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
    env.update(PYTHONIOENCODING="utf-8", PYTHONDONTWRITEBYTECODE="1")
    code = (
        "import serving._core as c\n"
        "print(c.__file__)\n"
        "print(','.join(sorted(n for n in vars(c) if not n.startswith('__'))))\n"
    )
    proc = subprocess.run(
        [sys.executable, "-X", "utf8", "-B", "-c", code],
        cwd=tmp_path, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=120,
    )
    assert proc.returncode == 0, proc.stderr[-2000:]
    loaded_from, names = proc.stdout.strip().splitlines()[-2:]
    assert Path(loaded_from).resolve() == (pkg / "_core.py").resolve(), "tmp 사본이 아닌 모듈을 import 했다"
    assert REQUIRED_CORE_NAMES <= set(names.split(","))
    assert listing() == before, "import 가 파일을 만들거나 바꿨다"


# ══════════════════════════════════════════════════════════════════════
# 6 — 노트북 금지 패턴 (build_notebook.validate)
# ══════════════════════════════════════════════════════════════════════
def test_validate_flags_lgb_file_api_and_serving_import():
    """`model_file=` 호출과 `import serving` 이 노트북 금지 흔적으로 잡힌다."""
    nb = _code_nb(
        'b = lgb.Booster(model_file="x")',
        "import serving",
        "x = 1\nprint(x)",
    )
    assert set(build_notebook.validate(nb)["strays"]) == {LGB_FILE_API, SERVING_IMPORT}


@pytest.mark.parametrize("source,expected", [
    ("booster.save_model('m.txt')", LGB_FILE_API),
    ("m = lgb.Booster(model_file = p)", LGB_FILE_API),
    ("from serving import load_bundle", SERVING_IMPORT),
    ("from serving._core import bundle_predict", SERVING_IMPORT),
    ("if True:\n    import serving.bundle", SERVING_IMPORT),
])
def test_validate_flags_variants(source, expected):
    """금지 패턴의 변형(저장 API·from-import·들여쓴 import)도 잡힌다."""
    assert build_notebook.validate(_code_nb(source))["strays"] == [expected]


def test_validate_ignores_comments_and_allowed_forms():
    """주석·마크다운에서의 언급과 허용 형태(`model_str=`, 다른 이름의 모듈)는 잡지 않는다."""
    nb = _code_nb(
        "# model_file= 은 금지",
        "    # import serving 도 금지",
        'b = lgb.Booster(model_str=text)',
        "import servings_util\nx = 1",
        markdown=("`Booster(model_file=...)` 는 한글 경로를 열지 못한다. `import serving` 금지.",),
    )
    assert build_notebook.validate(nb)["strays"] == []


def test_real_notebook_sources_have_no_strays():
    """현재 src 로 조립한 노트북에 금지 흔적이 없다(조립만 하고 파일은 쓰지 않는다)."""
    assert build_notebook.validate(build_notebook.build())["strays"] == []


# ══════════════════════════════════════════════════════════════════════
# 7 — 최종 게이트 강제 (finalize_notebook.check_final_gate)
# ══════════════════════════════════════════════════════════════════════
def _write_gate(out_dir: Path, rows: list[tuple[str, bool]]) -> None:
    """`save_table` 과 같은 형식(UTF-8 BOM)으로 gate6_final.csv 를 쓴다."""
    tbl = out_dir / "tables"
    tbl.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows, columns=["점검", "통과"]).to_csv(
        tbl / "gate6_final.csv", index=False, encoding="utf-8-sig"
    )


def test_final_gate_all_true_passes(tmp_path, monkeypatch):
    """게이트 표가 전부 True 면 미통과 항목이 없다."""
    monkeypatch.setattr(finalize_notebook, "OUTPUT_DIR", tmp_path)
    _write_gate(tmp_path, [("예측결과 336행·결측 0", True), ("서비스 번들 2종 생성·sha256 무결성", True)])
    assert finalize_notebook.check_final_gate() == []


def test_final_gate_reports_failed_row(tmp_path, monkeypatch):
    """False 인 행의 점검명만 돌려준다."""
    monkeypatch.setattr(finalize_notebook, "OUTPUT_DIR", tmp_path)
    _write_gate(tmp_path, [
        ("예측결과 336행·결측 0", True),
        ("평가 번들 재로드 예측 == 메모리 예측(비트)", False),
        ("제출 대상 개인정보 0건", True),
    ])
    assert finalize_notebook.check_final_gate() == ["평가 번들 재로드 예측 == 메모리 예측(비트)"]


def test_final_gate_missing_file_is_failure(tmp_path, monkeypatch):
    """게이트 표가 없으면 그 자체가 미통과 1건이다."""
    monkeypatch.setattr(finalize_notebook, "OUTPUT_DIR", tmp_path)
    assert finalize_notebook.check_final_gate() == ["gate6_final.csv 없음"]


# ══════════════════════════════════════════════════════════════════════
# 8 — 재현성 비교 대상 (check_reproducibility)
# ══════════════════════════════════════════════════════════════════════
BUNDLE_TABLE_COLS = ["번들", "모드", "bundle_id", "파일", "sha256", "bytes", "트리수", "학습행수"]


def _bundle_table(sha: str = "ab" * 32) -> pd.DataFrame:
    """ch6_model_bundles.csv 와 같은 컬럼의 작은 표."""
    return pd.DataFrame(
        [["eval", "FAST", "eval-fast-0123456789ab", "gate.lgb", sha, 1234, 50, 4000],
         ["deploy", "FAST", "deploy-fast-ba9876543210", "manifest.json", "cd" * 32, 567, 0, 4300]],
        columns=BUNDLE_TABLE_COLS,
    )


def test_bundle_table_is_reproducibility_target():
    """모델 번들 sha256 표가 재현성 비교 대상에 들어 있다."""
    assert "ch6_model_bundles" in check_reproducibility.TARGET_TABLES


def test_bundle_columns_are_not_timing():
    """번들 표의 어떤 컬럼도 실행시간으로 오인돼 비교에서 빠지지 않는다."""
    assert check_reproducibility._is_timing_col("학습시간(초)")   # 판정기가 실제로 동작한다
    assert [c for c in BUNDLE_TABLE_COLS if check_reproducibility._is_timing_col(c)] == []


def _bundle_row(result: pd.DataFrame) -> pd.Series:
    """비교 결과에서 ch6_model_bundles 행."""
    row = result[result["표"] == "ch6_model_bundles"]
    assert len(row) == 1
    return row.iloc[0]


def test_compare_new_table_ok_only_when_allowed(tmp_path, monkeypatch):
    """기준에 없는 신규 표는 `new_ok_if_absent=True` 일 때만 일치로 본다."""
    monkeypatch.setattr(check_reproducibility, "TBL_DIR", tmp_path)
    _bundle_table().to_csv(tmp_path / "ch6_model_bundles.csv", index=False, encoding="utf-8-sig")

    def reader(name):
        return None

    ok = _bundle_row(check_reproducibility.compare(read_baseline=reader, new_ok_if_absent=True))
    assert bool(ok["일치"]) is True
    assert ok["사유"] == "기준에 없음(신규 표)"

    ng = _bundle_row(check_reproducibility.compare(read_baseline=reader, new_ok_if_absent=False))
    assert bool(ng["일치"]) is False
    assert ng["사유"] == "파일 없음"


def test_compare_detects_sha_change(tmp_path, monkeypatch):
    """같은 번들 표는 일치, sha256 한 칸이 다르면 불일치로 나온다(모델 바이트 재현성 증명)."""
    monkeypatch.setattr(check_reproducibility, "TBL_DIR", tmp_path)
    monkeypatch.setattr(check_reproducibility, "TARGET_TABLES", ["ch6_model_bundles"])
    path = tmp_path / "ch6_model_bundles.csv"
    _bundle_table().to_csv(path, index=False, encoding="utf-8-sig")

    same = _bundle_row(check_reproducibility.compare(
        read_baseline=lambda n: pd.read_csv(path, encoding="utf-8-sig")))
    assert bool(same["일치"]) is True
    assert same["비교 셀 수"] == 2 * len(BUNDLE_TABLE_COLS)
    assert same["제외 컬럼(실행시간)"] == "-"

    diff = _bundle_row(check_reproducibility.compare(read_baseline=lambda n: _bundle_table("ef" * 32)))
    assert bool(diff["일치"]) is False
    assert diff["사유"] == "문자 불일치"


# ══════════════════════════════════════════════════════════════════════
# 9 — 개인정보 스캔 정규식 (s10 은 import 하지 않고 소스에서 추출)
# ══════════════════════════════════════════════════════════════════════
def _privacy_pattern(label: str) -> str:
    """src/s10_package.py 의 `PRIVACY_PATTERNS[label]` 문자열 리터럴을 AST 로 꺼낸다."""
    tree = ast.parse((PROJECT_ROOT / "src" / "s10_package.py").read_text(encoding="utf-8"))
    node = _defining_node(tree, "PRIVACY_PATTERNS")
    assert node is not None and isinstance(node.value, ast.Dict)
    for k, v in zip(node.value.keys, node.value.values):
        if isinstance(k, ast.Constant) and k.value == label:
            return ast.literal_eval(v)
    raise AssertionError(f"PRIVACY_PATTERNS 에 '{label}' 이 없다")


# 개인정보 스캔(10.6절)은 tests/*.py 도 읽는다 → 경로 형태 문자열은 조각을 이어 만든다
_WIN_PATH = "C:" + "\\" + "Users" + "\\" + "x"          # 실제 역슬래시 1개
_WIN_PATH_ESCAPED = "c:" + "\\\\" + "users" + "\\\\" + "x"  # JSON·repr 로 이스케이프된 형태


@pytest.mark.parametrize("pattern_source", ["s10", "finalize"])
def test_windows_path_pattern_catches_backslash_not_plus(pattern_source):
    """'Windows 절대경로' 정규식은 실제 역슬래시 경로를 잡고, `C:+Users` 는 잡지 않는다."""
    pat = (_privacy_pattern("Windows 절대경로") if pattern_source == "s10"
           else finalize_notebook.SCAN_PATTERNS["Windows 절대경로"])
    assert re.search(pat, _WIN_PATH)
    assert re.search(pat, _WIN_PATH_ESCAPED)
    assert re.search(pat, "C:+Users") is None
    assert re.search(pat, "C:Users") is None
