"""src/ 의 순수 함수·상수 → serving/_core.py 생성 (서빙 코드 한 벌 유지).

왜 필요한가
-----------
서빙 패키지는 `src/sNN_*.py` 를 import 할 수 없다. 그 모듈들은 import 하는 순간
해당 장 전체(데이터 적재·학습·그림 저장)를 실행하기 때문이다. 그렇다고 전처리·피처
함수를 손으로 복사하면 반드시 드리프트한다(학습과 서빙이 다른 피처를 만들게 된다).

그래서 `build_notebook.py` 와 같은 원칙("코드는 한 벌")으로, 지정한 이름의 **최상위
함수·상수의 원문**을 AST 로 추출해 `serving/_core.py` 를 생성한다. 생성 파일은 커밋하고,
테스트가 `--check` 로 src 와의 동기화를 강제한다.

사용법
------
    python tools/build_serving_core.py          # 생성
    python tools/build_serving_core.py --check  # src 와 다르면 종료코드 1
"""
from __future__ import annotations

import ast
import builtins
import hashlib
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = PROJECT_ROOT / "serving" / "_core.py"

# (상대경로, 추출할 최상위 이름) — 파일 안의 원래 순서대로 나온다
SPEC: list[tuple[str, list[str]]] = [
    ("src/s01_diagnose.py", [
        "POWER_COLS", "restore_hours", "build_datetime_index", "flag_and_repair",
        "add_targets", "build_operating_calendar",
    ]),
    ("src/s02_features.py", [
        "HOLIDAYS_2021", "FEATURE_LABELS", "_label", "add_calendar_features", "SAFE_LAGS",
        "build_origin_frame", "add_lag_features", "add_origin_stats",
        "add_production_weather_features", "FEATURE_GROUPS", "FEATURE_COLS", "build_features",
    ]),
    ("src/s10_package.py", ["bundle_predict", "manifest_core_sha256"]),
]

HEADER = '''\
# AUTO-GENERATED by tools/build_serving_core.py — 직접 수정하지 마라.
#
# 출처: {sources}
# 노트북(자원최적화_제안모델.ipynb)과 **같은 원문**이다. src 를 고친 뒤
#   python tools/build_serving_core.py
# 로 다시 생성한다. tests/test_serving_codegen.py 가 동기화를 강제한다.
"""서빙 코어 — 전처리·피처·번들 예측 (src 원문 추출본, import 부작용 없음)."""
import hashlib
import json

import numpy as np
import pandas as pd
'''


def _top_level_names(node: ast.stmt) -> list[str]:
    """최상위 문장이 정의하는 이름들."""
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        return [node.name]
    if isinstance(node, ast.Assign):
        return [t.id for t in node.targets if isinstance(t, ast.Name)]
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return [node.target.id]
    return []


def extract(relpath: str, names: list[str]) -> list[tuple[str, str]]:
    """파일에서 지정 이름의 최상위 정의 원문을 (이름, 원문) 목록으로 뽑는다."""
    source = (PROJECT_ROOT / relpath).read_text(encoding="utf-8")
    tree = ast.parse(source)
    wanted = set(names)
    # 같은 이름이 최상위에서 두 번 정의되면 노트북(마지막 정의)과 추출본(첫 정의)이 갈라진다
    counts: dict[str, int] = {}
    for node in tree.body:
        for n in _top_level_names(node):
            counts[n] = counts.get(n, 0) + 1
    dup = sorted(n for n in wanted if counts.get(n, 0) > 1)
    if dup:
        raise SystemExit(f"[FAIL] {relpath} 에서 두 번 이상 정의된 이름: {dup}")
    lines = source.splitlines(keepends=True)
    found: list[tuple[str, str]] = []
    for node in tree.body:
        hit = [n for n in _top_level_names(node) if n in wanted]
        if hit:
            text = ast.get_source_segment(source, node)
            decorators = getattr(node, "decorator_list", [])
            if decorators:   # get_source_segment 는 def 줄부터 잘라 데코레이터를 빠뜨린다
                start = min(d.lineno for d in decorators)
                text = "".join(lines[start - 1:node.lineno - 1]) + text
            found.append((hit[0], text))
            wanted -= set(hit)
    if wanted:
        raise SystemExit(f"[FAIL] {relpath} 에서 찾지 못한 이름: {sorted(wanted)}")
    return found


def render() -> str:
    """생성 파일 전체 텍스트(LF)."""
    parts = [HEADER.format(sources=", ".join(rel for rel, _ in SPEC))]
    for relpath, names in SPEC:
        for name, text in extract(relpath, names):
            digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:12]
            parts.append(f"\n\n# ── {relpath} :: {name}  (sha256 {digest}) ──\n{text}\n")
    return "".join(parts)


def free_names(code: str) -> set[str]:
    """생성 코드의 함수들이 참조하지만 어디에도 정의되지 않은 전역 이름.

    새 의존 상수가 src 에 생겼는데 SPEC 에 빠뜨리면 여기서 잡힌다.
    """
    tree = ast.parse(code)
    module_names = {"np", "pd", "json", "hashlib"}
    for node in tree.body:
        module_names.update(_top_level_names(node))
    missing: set[str] = set()
    for node in tree.body:
        # 최상위 대입문의 값(예: FEATURE_COLS = [.. FEATURE_GROUPS ..])도 검사한다
        if isinstance(node, (ast.Assign, ast.AnnAssign)) and node.value is not None:
            for sub in ast.walk(node.value):
                if isinstance(sub, ast.Name) and isinstance(sub.ctx, ast.Load):
                    if sub.id not in module_names and not hasattr(builtins, sub.id):
                        # 컴프리헨션 변수는 그 안에서 정의된다
                        comp_vars = {
                            t.id for c in ast.walk(node.value)
                            if isinstance(c, ast.comprehension)
                            for t in ast.walk(c.target) if isinstance(t, ast.Name)
                        }
                        if sub.id not in comp_vars:
                            missing.add(sub.id)
            continue
        if not isinstance(node, ast.FunctionDef):
            continue
        local: set[str] = set()
        for sub in ast.walk(node):
            if isinstance(sub, ast.arg):
                local.add(sub.arg)
            elif isinstance(sub, ast.Name) and isinstance(sub.ctx, (ast.Store, ast.Del)):
                local.add(sub.id)
            elif isinstance(sub, (ast.FunctionDef, ast.Lambda)) and sub is not node:
                if isinstance(sub, ast.FunctionDef):
                    local.add(sub.name)
            elif isinstance(sub, (ast.Import, ast.ImportFrom)):
                for alias in sub.names:
                    local.add((alias.asname or alias.name).split(".")[0])
        for sub in ast.walk(node):
            if isinstance(sub, ast.Name) and isinstance(sub.ctx, ast.Load):
                if sub.id not in local and sub.id not in module_names and not hasattr(builtins, sub.id):
                    missing.add(sub.id)
    return missing


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = render()
    missing = free_names(text)
    if missing:
        print(f"[FAIL] 생성 코드에 정의되지 않은 이름: {sorted(missing)} — SPEC 에 추가하라", file=sys.stderr)
        return 1
    data = text.encode("utf-8")   # write_text 는 Windows 에서 CRLF 로 바꾼다 → 바이트로 쓴다
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != data:
            print("[FAIL] serving/_core.py 가 src 와 다르다 — python tools/build_serving_core.py", file=sys.stderr)
            return 1
        print("[OK] serving/_core.py 가 src 와 일치한다")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(data)
    print(f"[OK] {OUTPUT.relative_to(PROJECT_ROOT).as_posix()} ({len(data):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
